---
platform: linux

image_resource:
  type: docker-image
  source: { repository: hseeberger/scala-sbt }

inputs:
  - name: greenscreen-source

run:
  path: greenscreen-source/deployment/concourse/tasks/runUnitTests.sh
